version: '3'

services:
  web:
    container_name: web-vue
    build: ./docker-front
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./front:/app
    links:
      - rails
    tty: true
    stdin_open: true
    command:  "npm run serve"
  db:
      image: postgres
      environment:
        POSTGRES_HOST_AUTH_METHOD: 'trust'
        POSTGRES_PASSWORD: 'postgres'
      volumes:
        - ./server/tmp/db:/var/lib/postgresql/data
  rails:
    build: ./server/.
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/myapp
    ports:
      - "3000:3000"
    links:
      - db
