default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test

production:
  adapter:  mysql2
  encoding: utf8
  pool:     5
  timeout:  5000
  username: 9da729a525fc3096f3c46a2dff93ea05
  password: 47fb3Rkj89iTCsWQhFVREm3
  database: 9da729a525fc3096f3c46a2dff93ea05
  host:     mysql-2.mc.lolipop.lan
